import { defineField, FieldType } from 'twenty-sdk/define';
import {
  QUOTE_OBJECT_UNIVERSAL_IDENTIFIER,
  QUOTE_PDF_FILE_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/quote-fields';

export default defineField({
  universalIdentifier: QUOTE_PDF_FILE_FIELD_UNIVERSAL_IDENTIFIER,
  objectUniversalIdentifier: QUOTE_OBJECT_UNIVERSAL_IDENTIFIER,
  type: FieldType.FILES,
  name: 'pdfFile',
  label: 'Quote PDF',
  description: 'The finalized PDF generated by Invoify.',
  icon: 'IconFileTypePdf',
  universalSettings: { maxNumberOfValues: 1 },
});
